version: 2
jobs:
  build:
    working_directory: ~/devops-starter
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: update-yarn
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
